### ISSUE TITLE
Bug: airtable_views.california_transit_map_services_gtfs_services_association_x_gtfs_service_data_services external dependencies not complete

### ISSUE THREAD

**Issue by evansiroky** [cal-itp/data-infra#1080]
**Describe the bug**

It appears that the `airtable_views.california_transit_map_services_gtfs_services_association_x_gtfs_service_data_services` external dependency DAGs are not all being registered properly in airflow.

**To Reproduce**

The DAG defines the external dependencies as follows:

```yml
external_dependencies:
  - airtable_loader: california_transit_services
  - airtable_loader: california_transit_gtfs_service_data
```

However, this is what shows up in Airflow (note the single external dependency):

<img width="664" alt="Screen Shot 2022-02-13 at 11 18 33 PM" src="https://user-images.githubusercontent.com/3112493/153817721-8ffb80d4-4d52-48ed-a119-06b755007847.png">

**Expected behavior**

There should be 2 external dependencies instead of 1.

**Additional context**

This may be happening in other DAG tasks as well.
