### ISSUE TITLE
add [API_KEY] template in `agencies.yml`

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#123]
We should create a secrets file that contains the API key for the agencies compose of API keys

ie, 

`secrets.yml`
```
api_key:
  itp_id: 7
  rt_key: {SOME_KEY}
  schedule_key: {SOME_KEY}
```

and then add logic in the `agencies.yml` to handle it using templating. Jinja might be useful here but curious for thoughts @lottspot @machow @e-lo
