### ISSUE TITLE
Fix github action that is supposed to build the new gtfs-rt-parser image

### ISSUE THREAD

**Issue by atvaccaro** [cal-itp/data-infra#1304]
I probably misinterpeted how this selector works.

```yaml
on:
  push:
    branches:
      - 'master'
    paths:
      - 'jobs/gtfs-rt-parser/**'
```

This isn't super urgent, as the image can be rebuilt manually for now. But it should be fixed next sprint IMO.
