### ISSUE TITLE
Changing structure of agencies.yml

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#146]
cc @themightychris @hunterowens @lottspot, does this format for `agencies.yml` work for you?

Currently, `agencies.yml` is structured as 1 entry per agency, with 3 kinds of info

* their name
* their itp_id
* fields for different kinds of feeds (e.g. gtfs_schedule_url, gtfs_rt_urls)

E.g.

```yaml
ac-transit:
  agency_name: AC Transit
  gtfs_schedule_url:
    - https://api.actransit.org/transit/gtfs/download?token=2512B81107A09D2DC44895CDDC650D47
  gtfs_rt_urls:
    vehicle_positions:
      - https://api.actransit.org/gtfsrt/vehicles?token=2512B81107A09D2DC44895CDDC650D47
    trip_updates:
      - https://api.actransit.org/gtfsrt/tripupdates?token=2512B81107A09D2DC44895CDDC650D47
    service_alerts:
      - https://api.actransit.org/gtfsrt/alerts?token=2512B81107A09D2DC44895CDDC650D47
  itp_id: 4
```

However, there are 2 limitations

* **nesting**: there are 3 different gtfs_rt feed types (vehicle_positions, trip_updates), nested under gtfs_rt_urls
* **multiple feeds within agency are represented by lists**: note that gtfs_schedule_url corresponds to a list. This is because a couple agencies have multiple feeds. This means we have to make sure that if an agency has feed 1 and feed 2, that all urls for feed 1 are the first list item everywhere. (currently being [violated in agencies.yml](https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml#L323-L327)).

### Proposal

**One solution suggested by @themightychris** is to have agency entries be assumed to only contain a single url by default. I would suggest in addition that we unnest gtfs_rt_urls. In this case, the yaml above would become...

```yaml
ac-transit:
  agency_name: AC Transit
  gtfs_schedule_url: https://api.actransit.org/transit/gtfs/download?token=2512B81107A09D2DC44895CDDC650D47
  gtfs_rt_vehicle_position_url: https://api.actransit.org/gtfsrt/vehicles?token=2512B81107A09D2DC44895CDDC650D47
  gtfs_rt_trip_updates_url: https://api.actransit.org/gtfsrt/tripupdates?token=2512B81107A09D2DC44895CDDC650D47
  gtfs_rt_service_alerts_url: https://api.actransit.org/gtfsrt/alerts?token=2512B81107A09D2DC44895CDDC650D47
  itp_id: 4
```

In the case where there are multiple feeds, I would suggest we add a feed field that is a list with the same urls:

```yaml
ac-transit:
  agency_name: AC Transit
  feeds:
      - gtfs_schedule_url: https://api.actransit.org/transit/gtfs/download?token=2512B81107A09D2DC44895CDDC650D47
        gtfs_rt_vehicle_position_url: https://api.actransit.org/gtfsrt/vehicles?token=2512B81107A09D2DC44895CDDC650D47
        gtfs_rt_trip_updates_url: https://api.actransit.org/gtfsrt/tripupdates?token=2512B81107A09D2DC44895CDDC650D47
        gtfs_rt_service_alerts_url: https://api.actransit.org/gtfsrt/alerts?token=2512B81107A09D2DC44895CDDC650D47
      - <additional feeds>
  itp_id: 4
```

### Migrating

The pipeline shouldn't need to continue supporting the old format, since it's used during extraction (which is `latest_only`). We'll need to modify..

* [generate_provider_list](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_downloader/generate_provider_list.py) to work off the new format
* maybe [download_data](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_downloader/download_data.py#L111), which saves a portion of agencies.yml as status.csv

### Limitations

One issue with the above proposal (and current structure) is that if an itp_id is inaccurate and corrected, the warehouse sees it as creating new feeds, since feeds do not have a unique id of their own. This is probably okay if we don't think we'll need to correct itp_id much, or are okay with the data being wrong before the point of correction. (i.e. if we had one file defining feeds, and another the association between feed and itp_id, we wouldn't have this problem, but it would also be harder for a human to update by hand...).

**Comment by hunterowens** [comment]
this SGTM!

**Comment by hunterowens** [comment]
Do we want to merge #123 before you start on the refactor here?

**Comment by e-lo** [comment]
I really like this approach because it explicitly recognizes the relationships between the Realtime and Static feeds and needing to keep them "together".

I have one additional thought to consider, which is potentially having a list of `feeds.yml` (same bundled list) with a `feed_id` which then would relate (many to many) to `agency.yml`.  

Advantages

- reduces duplication of validation and status'
- recognizes relationships which occur between feeds and agencies (currently would have to match the URLs)

**Comment by machow** [comment]
@hunterowens if it works for you--I would flip the order, and merge a PR for this first. That will allow us to implement for gtfs schedule extraction, and allow @lottspot to get a version of gtfs rt extraction up, while we get all the tokens / the spreadsheet in order! (For example, we could just use a github action to inject all the api_keys into agencies.yml, for both schedule and rt extraction to use)

To @e-lo's point--I definitely think separating feeds and agencies into separate files is ideal from the pipeline's pov. It would let us work off a single key (a feed_id), and be able to correct itp_ids. It would allow treating some of the cal-itp spreadsheets as a source of truth (e.g. for giving an itp_id an agency_name).

In this case we could consider the top-level field being used in agencies.yml as essentially a feed_id:

**feeds.yml**

```yaml
# feed_id is ac-transit
ac-transit:
  # remove agency specific info...
  # agency_name: AC Transit
  gtfs_schedule_url: https://api.actransit.org/transit/gtfs/download?token=2512B81107A09D2DC44895CDDC650D47
  gtfs_rt_vehicle_position_url: https://api.actransit.org/gtfsrt/vehicles?token=2512B81107A09D2DC44895CDDC650D47
  gtfs_rt_trip_updates_url: https://api.actransit.org/gtfsrt/tripupdates?token=2512B81107A09D2DC44895CDDC650D47
  gtfs_rt_service_alerts_url: https://api.actransit.org/gtfsrt/alerts?token=2512B81107A09D2DC44895CDDC650D47
  itp_id: 4
```

For feeds with multiple entries, we split them into two top-level entries...

```yaml
# note the feed provider put here to make feed_id unique
union-city-transit--trillium:
  gtfs_schedule_url: ...
  ...
  itp_id: 350

union-city-transit--511:
  gtfs_schedule_url: ...
  ...
  itp_id: 350
```

**agencies.yml**

(note that this information probably already exists on a spreadsheet in a very similar format somewhere)

```yaml
- itp_id: 4
   agency_name: AC Transit
```

### Migrating

On the pipeline side, we would use `feed_id` in all the spots where `{itp_id}_{url_number}` are used. We already need to join to get things like agency name, so I suspect if anything it will be a bit simpler for the pipeline, but imagine having two files is tricky for people making the updates. A mitigating factor might be that we could pull relevant agency info (including itp_id) in from existing calitp spreadsheets, then we won't need to duplicate in this repo, just handling feed definitions.

**Comment by themightychris** [comment]
re: the original proposal (which it sounds like may fall off in favor of making feeds the top-level object) -- I think the 2nd example with:

```yaml
ac-transit:
    feeds:
        - gtfs_*
```

is concise enough that I don't think it would be worth having an alt syntax where a single-feed `gtfs_*` keys would be at the top-level outside a feeds array. Have an extra `feeds: -` and some line breaks for single-feed agencies isn't enough waste vs the gained clarity, consistency, and verifiability (e.g. w/ jsonschema) of just always having the `feeds:` array. I really like the approach of having an array of feeds under each agency or an array of agencies instead of having a named keying scheme like i was suggesting with that "default" business

**Comment by hunterowens** [comment]
Flipping the order works for me, thanks @machow. 

I'm a little concerned about this change (or at least creating a "feed_ID"), as I think we wanna not create another ID (or if we do) preserve the link of `feed_id` to `cal_itp_id`. However, given that the advice in the GTFS Guidlines is going to be to have a 1:1 mapping between agencies:feeds, I think having a bit of a hack (ie, the default being singular objects, the fallback being feeds: key) makes more sense to me? but I'm willing to be overruled here

**Comment by machow** [comment]
In the `feeds.yml` proposal, I think the ids would become something like `itp_id` and `feed_id` (rather than `url_number`). The major advantage would be that `feed_id` would be unique, so people wouldn't need to constantly combine `itp_id` and `url_number`.

But actually, now that you mention it--maybe the goto approach is to keep it all a single file `agencies.yml`, but use the top-level field name instead of url_number? So...

```yaml
ac-transit:
  agency_name: AC Transit
  feeds:

      # pipeline uses feed_id=ac-transit__1
      - gtfs_schedule_url: https://api.actransit.org/transit/gtfs/download?token=2512B81107A09D2DC44895CDDC650D47
        gtfs_rt_vehicle_position_url: https://api.actransit.org/gtfsrt/vehicles?token=2512B81107A09D2DC44895CDDC650D47
        gtfs_rt_trip_updates_url: https://api.actransit.org/gtfsrt/tripupdates?token=2512B81107A09D2DC44895CDDC650D47
        gtfs_rt_service_alerts_url: https://api.actransit.org/gtfsrt/alerts?token=2512B81107A09D2DC44895CDDC650D47

      # pipeline uses feed_id=ac-transit__2
      - <additional feeds>
  # schedule tables all have calitp_itp_id, calitp_feed_id, but the big benefit is calitp_feed_id is now unique
  # per feed (vs url_number, which had to be combined with itp_id). itp_id can be joined in via SQL rather
  # than baked into the data sitting in the gcs bucket, so we can change it
  itp_id: 4
```

**Comment by machow** [comment]
In any event, I'm on board with each entry containing `fields`. Can handle the change of format and whether to use a unique feed_id key as a separate issue. It sounds like @themightychris and @hunterowens are on board with the change to `agencies.yml`, so if it works for everyone, I can put a PR up for it :).

**Comment by hunterowens** [comment]
SG!

**Comment by e-lo** [comment]
Wanted to clarify if the feed validation would be duplicated for agencies
with combined feeds with other agencies?

..and

**Comment by e-lo** [comment]
(cutoff)

Making sure LA Metro case is handled

**Comment by machow** [comment]
Right now, the warehouse runs validation for every feed specified in `agencies.yml`. If the same feed url is given multiple times, it will do validation for each duplicate feed. Doing the validation is pretty cheap timewise, and (if I'm understanding) we should be able to filter out duplicate feeds before reporting (or setup special forms of reporting for combined feeds).

Is the LA Metro case this setup?:

* there is one big combined feed (for some itp_id; LA Metro)
* there are smaller feeds that make up the combined feed (with their own itp_ids)

Can you say a bit about how communication of validation results w/ LA Metro is different from other feeds?

**Comment by e-lo** [comment]
LA Metro has two feeds: [Rail and Bus](https://developer.metro.net/gtfs-schedule-data/)

**Comment by machow** [comment]
Can you expand on what it means to handle the LA Metro case?

**Comment by e-lo** [comment]
Rereading...I think I just don't understand the current proposal in its entirety.  Translating above to LA Metro case where feeds are complimentary c.t. AC Transit where they are duplicative:

```yaml
la-metro
  agency_name: Los Angeles Metro
  feeds:
      - gtfs_schedule_url: #...RAIL FEED
        gtfs_rt_vehicle_position_url: #...
        gtfs_rt_trip_updates_url: #...
        gtfs_rt_service_alerts_url: #...
      - gtfs_schedule_url: #.. BUS FEED
        gtfs_rt_vehicle_position_url: #...
        gtfs_rt_trip_updates_url: #...
        gtfs_rt_service_alerts_url: #...
ac-transit
  agency_name: AC Transit
  feeds:
      - gtfs_schedule_url: #...feed from MTC/511
        gtfs_rt_vehicle_position_url: #...
        gtfs_rt_trip_updates_url: #...
        gtfs_rt_service_alerts_url: #...
      - gtfs_schedule_url: #.....feed published by AC Transit (duplicative of 511 feed)
```

1. Would we generate separate reports for each feed in the list and then give reports/grades on ALL of them to the agencies ? 
2. Or should we not even list the feed published by AC transit itself?  (not sure what the immediate ramifications are of this, but there could be some in the long-term if AC decides to publish fields/extensions that MTC doesn't...probably not a huge risk)
