### ISSUE TITLE
Deciding what to do for reporting agencies with multiple feeds / duplicate feeds

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#154]
cc @e-lo @mcplanner @hunterowens 

## Problem

We will be generating reports and communicating with agencies about their feeds. However, there are at least two edge cases to consider..

* **Complimentary feeds**. Agencies like LA Metro that split their rail and bus data into two feeds
* **Duplicative feeds**. Agencies that might have multiple, identical feeds.

How should we generate reports in these cases? My sense is that in terms of effort...

* **easy**: generate report for each feed. Agencies with multiple feeds deal with 1 email or report link per feed.
* **medium**: mark duplicative feeds, and only generate 1 report for them. Agencies w/ complimentary feeds still get multiple reports.
* **hard**: do the above and also aggregate complimentary feeds into a single report. Could be by representing them as a single feed in the data (scary), or aggregating metrics by removing duplicative feeds and grouping by itp_id.

I'd imagine that if it only impacts a couple feeds, then the easy approach should be okay? And unless it's a very common issue or high impact, then would rule the hard approach out?

## Copying @e-lo's comment from #146:

Rereading...I think I just don't understand the current proposal in its entirety. Translating above to LA Metro case where feeds are complimentary c.t. AC Transit where they are duplicative:

```yaml
la-metro
  agency_name: Los Angeles Metro
  feeds:
      - gtfs_schedule_url: #...RAIL FEED
        gtfs_rt_vehicle_position_url: #...
        gtfs_rt_trip_updates_url: #...
        gtfs_rt_service_alerts_url: #...
      - gtfs_schedule_url: #.. BUS FEED
        gtfs_rt_vehicle_position_url: #...
        gtfs_rt_trip_updates_url: #...
        gtfs_rt_service_alerts_url: #...
ac-transit
  agency_name: AC Transit
  feeds:
      - gtfs_schedule_url: #...feed from MTC/511
        gtfs_rt_vehicle_position_url: #...
        gtfs_rt_trip_updates_url: #...
        gtfs_rt_service_alerts_url: #...
      - gtfs_schedule_url: #.....feed published by AC Transit (duplicative of 511 feed)
```

1. Would we generate separate reports for each feed in the list and then give reports/grades on ALL of them to the agencies ?
2. Or should we not even list the feed published by AC transit itself? (not sure what the immediate ramifications are of this, but there could be some in the long-term if AC decides to publish fields/extensions that MTC doesn't...probably not a huge risk)
