### ISSUE TITLE
Complete column description implementation in SqlToWarehouseOperator

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#325]
Key pieces

* calitp-py [sql_patch_comments](https://github.com/cal-itp/calitp-py/blob/main/calitp/sql.py#L165)
* [get_table](https://github.com/cal-itp/calitp-py/blob/main/calitp/sql.py#L58) - fetch a table and its metadata as a sqlalchemy Table. E.g. use `table_obj.columns.keys()` to get column names.
* See this [example of a task with fields](https://github.com/cal-itp/data-infra/blob/main/airflow/dags/gtfs_views/validation_stg_code_descriptions.py#L4-L6)

Let's add examples to sandbox that capture...

* adding a single field description
* using fields_from
  - with any
  - with specific fields

## Spec

```yaml
fields:
  column_a: some description
  column_b: another one
fields_from:
  table_a:
    - column_c
    - column_d
  table_b: any
  # or
  table_b:
    - any
```
