### ISSUE TITLE
Setup Storage and Archiving of GTFS-RT data

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#38]
once we complete #26, we need to begin the path of capturing all the GTFS-RT data in the state. 

Caltrans' GTFS guidelines suggest that we expect updates to GTFS-RT feed at least every 20 seconds, so I recommend a 20 second sample rate and archive on all the feeds.

Each [GTFS-RT Feed](https://developers.google.com/transit/gtfs-realtime) should contain the following elements. 
* Vehicle Positions 
* Trip Updates
* Alerts 

Some prior work in GTFS-RT processing can be found in @unreasonableman's [GTFU](https://github.com/cal-itp/gtfu) and the [following notebook](https://github.com/cal-itp/notebooks/blob/main/notebooks/gtfs-rt-performance.ipynb). 

Essentially, what I think we want to do is setup a cloud function or similar to do the following procedure on a schedule. It might make sense to overlap these triggers, but essentially each minute, you watch a feed for a minute (or more). credit to @thekaveman for the idea. 

```python
for agency in agencies: 
  download_gtfs_rt_and_save_to_gcs_with_timestamp(agency)
  sleep(20)
  download_gtfs_rt_and_save_to_gcs_with_timestamp(agency)
  sleep(20)
  download_gtfs_rt_and_save_to_gcs_with_timestamp(agency)

def   download_gtfs_rt_and_save_to_gcs_with_timestamp(agency):
  # snapshot function for an agency gcs bridge 
  r = requests.get(vehicle_pos)
  data  = process_into_compressed_parquet(r.data)
  save_to_gcs(data, timestamp=now()) 
```

Constraints: Every GTFS-RT feed is stateless, ie, we cannot go back in time. This makes using an airflow job to monitor them unappealing, as it means you need 100% uptime. Perhaps a set of long running overlapping tasks would work, but I kinda think we should outsource this to the high availability of lambda / cloud functions /etc

**Comment by hunterowens** [comment]
cc @machow @themightychris for looping in Jarvis folks.

**Comment by machow** [comment]
Going to try pulling some of the different pieces together into a snippet, so it's in one place. Adding some thoughts on things that will make consuming the data in the pipeline easier down the road :).

## 1. RT urls

The urls for realtime feeds are stored in this [agencies.yml file](https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml#L7). Here's an example entry:

```
ac-transit:
  agency_name: AC Transit
  gtfs_schedule_url:
    - https://api.actransit.org/transit/gtfs/download?token=2512B81107A09D2DC44895CDDC650D47
  gtfs_rt_urls:
    vehicle_positions:
      - https://api.actransit.org/gtfsrt/vehicles?token=2512B81107A09D2DC44895CDDC650D47
    trip_updates:
      - https://api.actransit.org/gtfsrt/tripupdates?token=2512B81107A09D2DC44895CDDC650D47
    service_alerts:
      - https://api.actransit.org/gtfsrt/alerts?token=2512B81107A09D2DC44895CDDC650D47
  itp_id: 4
```

## 2. Pulling data (in python)

```python
# pulled from the example notebook
from google.transit import gtfs_realtime_pb2
import requests

r = requests.get("https://api.actransit.org/gtfsrt/vehicles?token=2512B81107A09D2DC44895CDDC650D47")

# note that the code below can be used to parse the data
# but shouldn't be needed for this task of storing it
feed = gtfs_realtime_pb2.FeedMessage()
feed.ParseFromString(response.content)
```

## 3. Thoughts on next steps

* get urls from the `agencies.yml` file in this repo
  - handle when `agencies.yml` is updated (@hunterowens may need to decide whether updates follow airflow deploy or the repo; probably not too important for now; could trigger from airflow, etc..)
* download data every 20 seconds
  - needs to fail gracefully for bad urls
* save to a gcs bucket? 
  - I would vote for using the "gtfs-data" bucket that airflow is using
  - (and saving to something like "gs://gtfs-data/rt")
