### ISSUE TITLE
Bug: The CI visualization can not find `manifest.json` file

### ISSUE THREAD

**Issue by fsalemi** [cal-itp/data-infra#3875]
**Describe the bug**
The PR visualization check is failing for this PR: [#3859](https://github.com/cal-itp/data-infra/pull/3859). The log shows the Create CI repost section of Pull Request Visualization Check  causes this error:
```
Runtime Error
  Got a state selector method, but no comparison manifest
``` 
According to the descriptions `visualize.py` script is trying to use dbt's state selection capabilities but can not find the `manifest.json` file it needs for comparison.   

**The Correct Solution: Generate and Cache the Manifest**
The right approach is to ensure the manifest.json file is generated and then made available to the visualization step. So the following two steps should be performed:
***_Generate the Manifest:_***
Add a CI step that runs dbt compile. This dbt command creates the `manifest.json` file in the target/ directory of the dbt project.
***_Cache the Manifest:_***
Add a CI step to cache the `manifest.json` file. This is crucial for subsequent steps to access it.

So the following lines should be added to the `deploy-dbt.yml` in the workflows folder right before the `Create CI report` section (in lline 353):

```
      - name: Compile dbt # Generate the manifest
        working-directory: warehouse
        run: poetry run dbt compile

      - name: Cache dbt manifest
        uses: actions/cache@v3
        id: dbt-manifest-cache
        with:
          path: warehouse/target/manifest.json
          key: dbt-manifest-${{ github.event.pull_request.base.sha }} # Cache based on the base branch SHA

```
