### ISSUE TITLE
Intake does not work with an unzipped shapefile

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#674]
See cal-itp/data-analyses#162

```python
import intake

# Need this to get credentials to read from GCS bucket
import gcsfs

# Open all the YAML files within the `catalogs` directory
catalog = intake.open_catalog("../catalogs/*.yml")

# error
catalog.test_shapefile_folder.read().head()
```

Where catalogs/sample_catalog.yml is...:

```yaml
metadata:
  version: 1
sources:
  test_shapefile_folder:
    driver: shapefile
    description: CalEnviroScreen 4.0
    args:
      urlpath: gs://calitp-analytics-data/data-analyses/bus_service_increase/CES4_final/CES4_final
      use_fsspec: true
  test_geoparquet:
    driver: geoparquet
    description: Description
    args:
      urlpath: gs://calitp-analytics-data/test_geoparquet.parquet
```
